apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-client
  labels:
    app: "{{ template "fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    role: client
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {{- range $sysctl := .Values.elasticsearch.sysctl }}
          {
            "name": "tune-sysctl",
            "image": "busybox",
            "imagePullPolicy": "IfNotPresent",
            "securityContext": {
              "privileged": true
            },
            "command": [
              "sysctl",
              "-w",
              "{{ $sysctl }}"
            ]
          }
          {{- end }}
        ]'
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        role: client
    spec:
      serviceAccount: "{{ template "fullname" . }}"
      serviceAccountName: "{{ template "fullname" . }}"
      containers:
      - name: elasticsearch
        image: munnerz/elasticsearch-k8s:lieutenant
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        resources:
{{ toYaml .Values.client.resources | indent 10 }}
        args:
        - start
        - --role=client
        - --namespace=$(KUBERNETES_NAMESPACE)
        - --plugins={{ .Values.elasticsearch.plugins }}
        - --podName=$(KUBERNETES_POD_NAME)
        - --statefulSetName={{ template "fullname" . }}-data
        env:
        - name: SERVICE
          value: {{ template "fullname" . }}-cluster
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - name: http
          containerPort: 9200
        - name: transport
          containerPort: 9300
