apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-kibana
  labels:
    app: {{ template "fullname" . }}-kibana
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    role: kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-kibana
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        role: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:5.2.2
        command:
        - /usr/share/kibana/bin/kibana
        ports:
        - name: http
          containerPort: 5601
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config
      volumes:
      - name: config
        configMap:
          name: {{ template "fullname" . }}-kibana
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-kibana
  labels:
    app: {{ template "fullname" . }}-kibana
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    role: kibana
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0"
    elasticsearch.url: http://{{ template "fullname" . }}:9200
    xpack.monitoring.ui.container.elasticsearch.enabled: true
