# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

plugins:
# this plugin is no longer required
# - name: "io.fabric8:elasticsearch-cloud-kubernetes:5.2.2"

minimumMasters: 2

sysctl:
- vm.max_map_count=262144

rbac:
  create: true
  # serviceAccountName: ""

pilot:
  repository: jetstackexperimental/pilot-elasticsearch
  tag: latest
  pullPolicy: Always

image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: 5.2.2
  pullPolicy: IfNotPresent
  ## This sets the group of the persistent volume created for
  ## the data nodes. This must be the same as the user that elasticsearch
  ## runs as within the container.
  fsGroup: 1000

nodePools:
- name: mixed
  replicas: 3

  roles:
  - master
  - client
  - data

  # nodeSelector:
  #   node-role.kubernetes.io/node: storage

  # podManagementPolicy: "Parallel"

  env:
    ES_JAVA_OPTS: -Djava.net.preferIPv4Stack=true -Des.cgroups.hierarchy.override=/ -Xms1g -Xmx1g

  resources:
    requests:
      cpu: '500m'
      memory: 1536Mi
    limits:
      cpu: '1'
      memory: 1536Mi

  # persistent sets persistent storage config
  persistence:
    # enabled will only have an effect if stateful is also true. If true,
    # the persistentVolumeClaims block of the StatefulSet will be set
    enabled: false
    # size of the volume
    # size: 30Gi
    # storageClass of the volume
    # storageClass: ""
